package EntityDemo.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class Entity_Behavior {
  public static void init(SNode thisNode) {
  }

  public static String call_classname_3292461007592895086(SNode thisNode) {
    return SPropertyOperations.getString(thisNode, "name") + "Bean";
  }
}
