package EntityDemo.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;

public interface IResourceContext_BehaviorDescriptor extends INamedConcept_BehaviorDescriptor {
}
