package EntityInstanceDemo.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class EntityInstanceDemo_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("abda99ad-b25a-4702-9c1d-2422009f9c87(EntityInstanceDemo)");

  public static Language get() {
    return (Language) MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
