package EntityInstanceDemo.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.impl.CompiledConceptDescriptor;
import jetbrains.mps.smodel.runtime.interpreted.StructureAspectInterpreted;

public class StructureAspectDescriptor implements jetbrains.mps.smodel.runtime.StructureAspectDescriptor {
  private static String[] stringSwitchCases_1htk8d_a0a0a = new String[]{"EntityInstanceDemo.structure.EAVExpression", "EntityInstanceDemo.structure.EntityAttributeValue", "EntityInstanceDemo.structure.EntityInstance", "EntityInstanceDemo.structure.InstanceRefExpression", "EntityInstanceDemo.structure.IntConstantExpression", "EntityInstanceDemo.structure.StringConstantExpression"};

  public StructureAspectDescriptor() {
  }

  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0a, conceptFqName)) {
      case 0:
        return new CompiledConceptDescriptor("EntityInstanceDemo.structure.EAVExpression", "jetbrains.mps.lang.core.structure.BaseConcept", false, new String[]{"jetbrains.mps.lang.core.structure.BaseConcept"}, new String[]{}, new String[]{});
      case 1:
        return new CompiledConceptDescriptor("EntityInstanceDemo.structure.EntityAttributeValue", "jetbrains.mps.lang.core.structure.BaseConcept", false, new String[]{"jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept"}, new String[]{}, new String[]{"attribute"});
      case 2:
        return new CompiledConceptDescriptor("EntityInstanceDemo.structure.EntityInstance", "jetbrains.mps.lang.core.structure.BaseConcept", false, new String[]{"jetbrains.mps.lang.core.structure.BaseConcept", "EntityDemo.structure.IResourceContext"}, new String[]{}, new String[]{"entity"});
      case 3:
        return new CompiledConceptDescriptor("EntityInstanceDemo.structure.InstanceRefExpression", "EntityInstanceDemo.structure.EAVExpression", false, new String[]{"EntityInstanceDemo.structure.EAVExpression"}, new String[]{}, new String[]{"entityInstance"});
      case 4:
        return new CompiledConceptDescriptor("EntityInstanceDemo.structure.IntConstantExpression", "EntityInstanceDemo.structure.EAVExpression", false, new String[]{"EntityInstanceDemo.structure.EAVExpression"}, new String[]{"value"}, new String[]{});
      case 5:
        return new CompiledConceptDescriptor("EntityInstanceDemo.structure.StringConstantExpression", "EntityInstanceDemo.structure.EAVExpression", false, new String[]{"EntityInstanceDemo.structure.EAVExpression"}, new String[]{"value"}, new String[]{});
      default:
        return StructureAspectInterpreted.getInstance().getDescriptor(conceptFqName);
    }
  }
}
