package EntityDemo.sandbox.sandbox3;

/*Generated by MPS */


public class AdBean {
  private String sd;
  private String gd;
  private String w;

  public AdBean() {
  }

  public void setSd(String value) {
    this.sd = value;
  }

  public void setGd(String value) {
    this.gd = value;
  }

  public void setW(String value) {
    this.w = value;
  }

  public String getSd() {
    return sd;
  }

  public String getGd() {
    return gd;
  }

  public String getW() {
    return w;
  }
}
