package EntityDemo.sandbox.sandbox3;

/*Generated by MPS */


public class AggBean {
  private String hodnota;
  private int cislo;
  private TtBean ttt;

  public AggBean() {
  }

  public void setHodnota(String value) {
    this.hodnota = value;
  }

  public void setCislo(int value) {
    this.cislo = value;
  }

  public void setTtt(TtBean value) {
    this.ttt = value;
  }

  public String getHodnota() {
    return hodnota;
  }

  public int getCislo() {
    return cislo;
  }

  public TtBean getTtt() {
    return ttt;
  }
}
