package EntityDemo.sandbox.sandbox3;

/*Generated by MPS */


public class TtBean {
  private String ggg;
  private String we;

  public TtBean() {
  }

  public void setGgg(String value) {
    this.ggg = value;
  }

  public void setWe(String value) {
    this.we = value;
  }

  public String getGgg() {
    return ggg;
  }

  public String getWe() {
    return we;
  }
}
