package EntityInstanceDemo.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class EAVExpression_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public EAVExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "EntityInstanceDemo.structure.EAVExpression";
  }
}
