package EntityInstanceDemo.behavior;

/*Generated by MPS */


public class InstanceRefExpression_BehaviorDescriptor extends EAVExpression_BehaviorDescriptor {
  public InstanceRefExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "EntityInstanceDemo.structure.InstanceRefExpression";
  }
}
