package EntityInstanceDemo.behavior;

/*Generated by MPS */


public class IntConstantExpression_BehaviorDescriptor extends EAVExpression_BehaviorDescriptor {
  public IntConstantExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "EntityInstanceDemo.structure.IntConstantExpression";
  }
}
