package EntityInstanceDemo.behavior;

/*Generated by MPS */


public class StringConstantExpression_BehaviorDescriptor extends EAVExpression_BehaviorDescriptor {
  public StringConstantExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "EntityInstanceDemo.structure.StringConstantExpression";
  }
}
