package EntityInstanceDemo.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.SNodePointer;
import java.util.Map;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsDescriptor;
import java.util.HashMap;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.ReferenceScopeProvider;
import jetbrains.mps.smodel.runtime.base.BaseReferenceScopeProvider;
import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class EntityAttributeValue_Constraints extends BaseConstraintsDescriptor {
  private static SNodePointer breakingNode_11vttj_a0a1a0a0a1a0b0a1a0 = new SNodePointer("r:9111e8ed-d42e-4012-89f2-75a6eef29e0a(EntityInstanceDemo.constraints)", "7947071536996654196");

  public EntityAttributeValue_Constraints() {
    super("EntityInstanceDemo.structure.EntityAttributeValue");
  }

  @Override
  protected Map<String, ReferenceConstraintsDescriptor> getNotDefaultReferences() {
    Map<String, ReferenceConstraintsDescriptor> references = new HashMap();
    references.put("attribute", new BaseReferenceConstraintsDescriptor("attribute", this) {
      @Override
      public boolean hasOwnScopeProvider() {
        return true;
      }

      @Nullable
      @Override
      public ReferenceScopeProvider getScopeProvider() {
        return new BaseReferenceScopeProvider() {
          @Override
          public Object createSearchScopeOrListOfNodes(final IOperationContext operationContext, final ReferenceConstraintsContext _context) {
            return SLinkOperations.getTargets(SLinkOperations.getTarget(SNodeOperations.cast(_context.getEnclosingNode(), "EntityInstanceDemo.structure.EntityInstance"), "entity", false), "attributes", true);
          }

          @Override
          public SNodePointer getSearchScopeValidatorNode() {
            return breakingNode_11vttj_a0a1a0a0a1a0b0a1a0;
          }
        };
      }
    });
    return references;
  }
}
