package EntityDemo.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class EntityDemo_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("1b935120-1e0a-4399-ae83-6bc660e9b22e(EntityDemo)");

  public static Language get() {
    return (Language) MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
