package EntityDemo.sandbox.sandbox1;

/*Generated by MPS */


public class Exx1Bean {
  private String opslaaa;

  public Exx1Bean() {
  }

  public void setOpslaaa(String value) {
    this.opslaaa = value;
  }

  public String getOpslaaa() {
    return opslaaa;
  }
}
