package EntityDemo.sandbox.sandbox;

/*Generated by MPS */


public class Entita1Bean {
  private String retazec;
  private boolean logicPremenna;

  public Entita1Bean() {
  }

  public void setRetazec(String value) {
    this.retazec = value;
  }

  public void setLogicPremenna(boolean value) {
    this.logicPremenna = value;
  }

  public String getRetazec() {
    return retazec;
  }

  public boolean getLogicPremenna() {
    return logicPremenna;
  }
}
