package EntityDemo.sandbox.sandbox;

/*Generated by MPS */


public class Entita2Bean {
  private Entita1Bean ent1ref;
  private Entita2Bean asd;
  private Entita1Bean asd1;
  private String ret2;

  public Entita2Bean() {
  }

  public void setEnt1ref(Entita1Bean value) {
    this.ent1ref = value;
  }

  public void setAsd(Entita2Bean value) {
    this.asd = value;
  }

  public void setAsd1(Entita1Bean value) {
    this.asd1 = value;
  }

  public void setRet2(String value) {
    this.ret2 = value;
  }

  public Entita1Bean getEnt1ref() {
    return ent1ref;
  }

  public Entita2Bean getAsd() {
    return asd;
  }

  public Entita1Bean getAsd1() {
    return asd1;
  }

  public String getRet2() {
    return ret2;
  }
}
