package EntityDemo.sandbox.sandbox;

/*Generated by MPS */


public class ExxBean {
  private Entita1Bean asd;

  public ExxBean() {
  }

  public void setAsd(Entita1Bean value) {
    this.asd = value;
  }

  public Entita1Bean getAsd() {
    return asd;
  }
}
